/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Header: typeof import('./../src/components/Header.vue')['default']
    MenuItem: typeof import('./../src/components/MenuList/MenuItem.vue')['default']
    MenuList: typeof import('./../src/components/MenuList/MenuList.vue')['default']
    ProjectPopper: typeof import('./../src/components/ProjectPopper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
